[font]
size = 11.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
opacity = 0.78
blur = true
dynamic_padding = true

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
